// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function GetMarket(arg1:number):Promise<entities.Market>;

export function GetMarkets():Promise<Array<entities.Market>>;

export function Greet(arg1:string):Promise<string>;
