// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMarket(arg1) {
  return window['go']['main']['App']['GetMarket'](arg1);
}

export function GetMarkets() {
  return window['go']['main']['App']['GetMarkets']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
